CREATE TABLE IF NOT EXISTS public.password_recovery (
  id_recovery INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario INTEGER NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE,
  email VARCHAR(100) NOT NULL,
  codigo VARCHAR(6) NOT NULL,
  token VARCHAR(100) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expira_em TIMESTAMP,
  utilizado_em TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_password_recovery_email
  ON public.password_recovery (email);

CREATE INDEX IF NOT EXISTS idx_password_recovery_token
  ON public.password_recovery (token);
